//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatorImaging.StaticMemberAnalyzer.Analysis {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SatorImaging.StaticMemberAnalyzer.Analysis.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Static field declaration order is wrong. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0001_Description {
            get {
                return ResourceManager.GetString("SMA0001_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reading &apos;{0}&apos; before initialize (WrongInit) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0001_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0001_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Uninitialized Field Access に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0001_Title {
            get {
                return ResourceManager.GetString("SMA0001_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Static field is trying to read value from static field declared in another type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0002_Description {
            get {
                return ResourceManager.GetString("SMA0002_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type &apos;{0}&apos; is referencing static field in type &apos;{1}&apos; (CrossRef) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0002_MessageFormat {
            get {
                return ResourceManager.GetString("SMA0002_MessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Static Cross Referencing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SMA0002_Title {
            get {
                return ResourceManager.GetString("SMA0002_Title", resourceCulture);
            }
        }
    }
}
